import { useState } from "react";
import { 
  Dialog, 
  DialogContent, 
  DialogHeader, 
  DialogTitle,
  DialogFooter
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Cpu, Send } from "lucide-react";

interface AIExplanationPopupProps {
  isOpen: boolean;
  title: string;
  content: string;
  section: string;
  onClose: () => void;
}

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

export function AIExplanationPopup({
  isOpen,
  title,
  content,
  section,
  onClose
}: AIExplanationPopupProps) {
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState("");
  const [showChat, setShowChat] = useState(false);

  const handleSendMessage = () => {
    if (!inputValue.trim()) return;
    
    // Add user message
    const newMessages = [
      ...chatMessages,
      { role: "user", content: inputValue }
    ];
    
    setChatMessages(newMessages);
    setInputValue("");
    
    // Simulate AI response based on the section and question
    setTimeout(() => {
      let response = "";
      
      // Generate contextual responses based on the section
      if (section === "marketPulse") {
        response = "The Market Pulse section shows the overall sentiment of the market today. The sentiment score is calculated based on various factors including price movements, volatility, and news sentiment analysis. A higher score indicates more positive market conditions.";
      } else if (section === "snapshot") {
        response = "The Market Snapshot provides a quick overview of what's happening across different market segments. The colored badges indicate whether an asset or index is up (green) or down (red) for the day.";
      } else if (section === "insights") {
        response = "These insights are generated by analyzing patterns in market data and news. They highlight important trends or anomalies that might affect your investment decisions. The 'Why This Matters' section explains the potential implications of each insight.";
      } else if (section === "sentiment") {
        response = "The Fear & Greed Index is a popular tool for measuring market sentiment. It ranges from Extreme Fear (0) to Extreme Greed (100). Historically, extreme readings often indicate potential market turning points - extreme fear can signal buying opportunities, while extreme greed may suggest caution.";
      } else if (section === "assets") {
        response = "This dashboard shows real-time performance of key assets across different categories. The percentage change is calculated based on the previous day's closing price. You can use this to quickly identify which assets or sectors are outperforming or underperforming today.";
      } else {
        response = "I'm here to help explain any aspect of the market news and data you see. Is there something specific you'd like to know more about?";
      }
      
      setChatMessages([...newMessages, { role: "assistant", content: response }]);
    }, 1000);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[500px] max-h-[80vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center">
            <Cpu className="h-5 w-5 mr-2 text-primary" />
            {title}
          </DialogTitle>
        </DialogHeader>
        
        <div className="flex-1 overflow-hidden flex flex-col">
          <ScrollArea className="flex-1 pr-4">
            <div className="space-y-4">
              <div className="text-sm text-muted-foreground">
                {content}
              </div>
              
              {showChat && (
                <>
                  <Separator />
                  
                  <div className="space-y-4 mt-4">
                    {chatMessages.map((message, index) => (
                      <div 
                        key={index} 
                        className={`flex ${
                          message.role === "user" ? "justify-end" : "justify-start"
                        }`}
                      >
                        <div 
                          className={`rounded-lg px-4 py-2 max-w-[80%] ${
                            message.role === "user" 
                              ? "bg-primary text-primary-foreground" 
                              : "bg-muted"
                          }`}
                        >
                          {message.content}
                        </div>
                      </div>
                    ))}
                  </div>
                </>
              )}
            </div>
          </ScrollArea>
          
          {!showChat && (
            <Button 
              className="mt-4 w-full" 
              onClick={() => setShowChat(true)}
            >
              Ask Follow-up Questions
            </Button>
          )}
          
          {showChat && (
            <div className="mt-4 flex items-center space-x-2">
              <Input
                placeholder="Ask a question..."
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyDown={handleKeyDown}
                className="flex-1"
              />
              <Button size="icon" onClick={handleSendMessage}>
                <Send className="h-4 w-4" />
              </Button>
            </div>
          )}
        </div>
        
        <DialogFooter className="sm:justify-start">
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
} 